### ISSUE TITLE
Change MusicNotationKit to MusicNotationCore in the project

### ISSUE THREAD

**Issue by drumnkyle** [drumnkyle/music-notation-core#112]
Change all references to MusicNotationKit to MusicNotationCore. The only place left, I believe is in the header of each file. You can do a search/replace for `// MusicNotationKit`

**Comment by massimobio** [comment]
Hello, I'd like to contribute to this project so I'm starting with something simple. #122

**Comment by drumnkyle** [comment]
Fixed by #122
