### ISSUE TITLE
Create types instead of using tuples for index

### ISSUE THREAD

**Issue by drumnkyle** [drumnkyle/music-notation-core#121]
For instance, change `NoteCollectionIndex` and others like it to a struct instead of a tuple of values.

**Comment by massimobio** [comment]
I'd be happy to help with some contributions and if possible I'd like to join the Slack channel as massimobio gmail. 
These simpler issues are a good way to try and get familiar with the code base.
I just pushed a PR #123 that converts the NoteCollectionIndex from tuple to Struct.

Any other tuples come to mind that I could tackle?

**Comment by drumnkyle** [comment]
Closed by #123
